### PR TITLE
Gradle chores

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by pdvrieze** [comment]
Please base the pull request on dev (which contains the current work)

The development happens mainly on the `dev` branch (which has newer versions), but also has the start of attempting splitting out Android/Jvm targets into separate submodules (rather than 2 variants in multiplatform - this is deprecated in kotlin multiplatform).

**Comment by sschuberth** [comment]
> Please base the pull request on dev (which contains the current work)

Done @pdvrieze.

**Review by pdvrieze — APPROVED** [review]
Some versions needed to be deleted. But otherwise should be merge. Thanks for the work

**Comment by sschuberth** [comment]
> Some versions needed to be deleted. But otherwise should be merge. Thanks for the work

Let me rebase once more to resolve conflicts.

**Comment by pdvrieze** [comment]
Thanks for the work. Now merged (with some small changes)

**Comment by sschuberth** [comment]
> Thanks for the work. Now merged (with some small changes)

You missed one spot 😉 https://github.com/pdvrieze/xmlutil/pull/207

**Pull request merged**
